=== wanderingivan/forumsite-example/src/test/resources/datasets/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (
	Users*,
	ForumThread*,
	Comment*
)>

<!ELEMENT Users EMPTY>
<!ATTLIST Users
	id CDATA #IMPLIED
	username CDATA #REQUIRED
	email CDATA #REQUIRED
	description CDATA #REQUIRED
	imageName CDATA #IMPLIED
>

<!ELEMENT ForumThread EMPTY>
<!ATTLIST ForumThread
	id CDATA #IMPLIED
	name CDATA #REQUIRED
	category CDATA #REQUIRED
	createdOn CDATA #REQUIRED
	lastUpdate CDATA #IMPLIED
	author_id CDATA #REQUIRED
>

<!ELEMENT Comment EMPTY>
<!ATTLIST Comment
	id CDATA #IMPLIED
	message CDATA #REQUIRED
	thread_id CDATA #REQUIRED
	comment_author_id CDATA #REQUIRED
>

=== wanderingivan/forumsite-example/src/test/resources/datasets/persistence-test-dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset PUBLIC "//UNKNOWN/" "test.dtd">
<dataset>

	<Users id="11" username="username1" password="password" email="email@email.com1"  description="No description" imageName="empty"/>
	<Users id="22" username="username2" password="password" email="email@email.com2"  description="No description" imageName="empty"/>
	<Users id="33" username="username3" password="password" email="email@email.com3"  description="No description" imageName="empty"/>

	<ForumThread id="11" name="threadname1" category="category" author_id="11" createdOn="2017-01-01" lastUpdate="2017-01-01"/>
	<ForumThread id="22" name="threadname2" category="category" author_id="11" createdOn="2017-01-01" lastUpdate="2017-01-01"/>
	<ForumThread id="33" name="threadname3" category="category" author_id="11" createdOn="2017-01-01" lastUpdate="2017-01-01"/>
	<ForumThread id="44" name="threadname4" category="category" author_id="11" createdOn="2017-01-01" lastUpdate="2017-01-01"/>
	
</dataset>
